name: website

on:
  push: 
    branches: [ master ]
  release:
    types: [ published ]
  workflow_dispatch:
    branches: [ master ]

jobs:
  publish-docs:
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0
      - name: Print Latest Tag For Debugging Purposes
        run: git tag --sort=committerdate | tail -1
      - uses: olafurpg/setup-scala@v13
      - name: Compile Project's Documentation
        run: sbt compileDocs
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Publishing Docs to NPM Registry
        run: sbt publishToNpm
        env: 
          NODE_AUTH_TOKEN: ${secrets.NPM_TOKEN}
